name: CMake build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # let all platforms run, regardless of failures
      fail-fast: false

      # Matrix of configurations
      matrix:
        os: [ ubuntu-latest ]
        build_type: [ Release ]
        c_compiler: [ gcc, clang ]
        device: [ cpu ]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            ftn_compiler: gfortran
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            ftn_compiler: gfortran

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Download libtorch
        id: libtorch
        shell: bash
        if: ${{ matrix.device == 'cpu' }}
        run: |
          wget "https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.1.0%2Bcpu.zip"
          echo "04f699d5181048b0062ef52de1df44b46859b8fbeeee12abdbcb9aac63e2a14b libtorch-cxx11-abi-shared-with-deps-2.1.0+cpu.zip" | sha256sum -c -
          unzip libtorch-cxx11-abi-shared-with-deps-2.1.0+cpu.zip
          echo "path=$(realpath libtorch)" >> "$GITHUB_OUTPUT"
          rm libtorch-cxx11-abi-shared-with-deps-2.1.0+cpu.zip

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.libtorch.outputs.path }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_FORTRAN_COMPILER=${{ matrix.ftn_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_PREFIX_PATH=${{ steps.strings.outputs.build-output-dir }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }}
