name: CMake build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # let all platforms run, regardless of failures
      fail-fast: false

      # Matrix of configurations
      matrix:
        os: [ ubuntu-latest ]
        build_type: [ Release ]
        c_compiler: [ gcc ]  # [ gcc, clang ]
        device: [ cpu, cuda ]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            ftn_compiler: gfortran
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            ftn_compiler: gfortran
            device: cpu

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Download libtorch (CPU)
        id: libtorch
        shell: bash
        if: ${{ matrix.device == 'cpu' }}
        run: |
          case ${{ matrix.device }} in
            "cpu")
              LIBTORCH_URL="https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.1.0%2Bcpu.zip"
              ;;
            "cuda")
              LIBTORCH_URL="https://download.pytorch.org/libtorch/cu121/libtorch-cxx11-abi-shared-with-deps-2.1.0%2Bcu121.zip"
              ;;
            *)
            echo -n "unknown option for device"
            exit 1
            ;;
          esac  

          # download & extract libtorch
          wget -q $LIBTORCH_URL -O libtorch.zip
          unzip -q libtorch.zip
          rm libtorch.zip
          
          # save path for later steps
          echo "path=$(realpath libtorch)" >> "$GITHUB_OUTPUT"

      - name: DEBUG
        run: |
          echo steps.strings.outputs.build-output-dir: ${{ steps.strings.outputs.build-output-dir }}
          echo steps.libtorch.outputs.path: ${{ steps.libtorch.outputs.path }}


      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_FORTRAN_COMPILER=${{ matrix.ftn_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_PREFIX_PATH=${{ steps.libtorch.outputs.path }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }}
